---
- name: Tomcat deployment playbook
  hosts: app       # Inventory hosts group / server to act on
  become: yes               # If to escalate privilege

  vars:
    tomcat_ver: 8.5.84                          # Tomcat version to install
    ui_manager_user: manager                    # User who can access the UI manager section only
    ui_manager_pass: Str0ngManagerPassw3rd      # UI manager user password
    ui_admin_username: admin                    # User who can access bpth manager and admin UI sections
    ui_admin_pass: Str0ngAdminPassw3rd          # UI admin password
  roles:
    - tomcat